# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3.4'

volumes:
  customsOrg:

networks:
  cr_network:
     external:
        name: cr_network

services:

  customsOrg:
    container_name: customsOrg
    image: hyperledger/fabric-peer:1.4
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_cr_network
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer0.customsOrg.chainrefund.com
      - CORE_PEER_ADDRESS=peer0.customsOrg.chainrefund.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.customsOrg.chainrefund.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.customsOrg.chainrefund.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.customsOrg.chainrefund.com:9051
      - CORE_PEER_LOCALMSPID=CustomsOrgMSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb_customs:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    volumes:
        - /var/run/:/host/var/run/
        - ~/crypto-config/peerOrganizations/customsOrg.chainrefund.com/peers/peer0.customsOrg.chainrefund.com/msp:/etc/hyperledger/fabric/msp
        - ~/crypto-config/peerOrganizations/customsOrg.chainrefund.com/peers/peer0.customsOrg.chainrefund.com/tls:/etc/hyperledger/fabric/tls
        - peer0.customsOrg.chainrefund.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    deploy:
       mode: replicated
       replicas: 1
       restart_policy:
          condition: on-failure
       placement:
           constraints:
              - node.hostname == ip-172-31-47-47
    ports:
       - 9051:9051
    networks:
       cr_network:
          aliases:
             - customsOrg

  couchdb_customs:
    container_name: couchdb_customs
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    deploy:
       mode: replicated
       replicas: 1
       restart_policy:
          condition: on-failure
       placement:
          constraints:
             - node.hostname == ip-172-31-47-47
    ports:
       - "6984:5984"
    networks:
       - cr_network

  zookeeper.customs.com:
    container_name: zookeeper.customs.com
    image: hyperledger/fabric-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 32182
      ZOOKEEPER_TICK_TIME: 2000
    networks:
    - cr_network

  kafka.customs.com:
    container_name: kafka.customs.com
    image: hyperledger/fabric-kafka
    depends_on:
    - zookeeper.customs.com
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper.customs.com:2182
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka.customs.com:9093
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_MESSAGE_MAX_BYTES=1048576 # 1 * 1024 * 1024 B
      - KAFKA_REPLICA_FETCH_MAX_BYTES=1048576 # 1 * 1024 * 1024 B
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - KAFKA_LOG_RETENTION_MS=-1
      - KAFKA_MIN_INSYNC_REPLICAS=1
      - KAFKA_DEFAULT_REPLICATION_FACTOR=1
    networks:
    - cr_network

